name: Deploy Website

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: setup git configuration
      run: |
        git config --global user.email "tanner.barlow.dev@gmail.com"
        git config --global user.name "Tanner Barlow"
        git remote rm origin
        git remote add origin https://${GITHUB_TOKEN}@github.com/tbarlow12/personal-website-beta.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    - name: npm install and deploy
      run: |
        npm install
        npm run deploy
      env:
        CI: true
